### PR TITLE
Update script to file bugs to JIRA

### PR DESCRIPTION
**Pull request by kweerious**
Remove Pivotal mentions
Add JSON keys/values for JIRA issue creation

https://metacloud.jira.com/browse/COS-226

https://github.com/piston/git-tools/pull/14
https://github.com/piston/jenkins/pull/1 (for viewing only)

### CODE REVIEW

**Comment by kweerious** [comment]
Better example with all env vars provided:

https://metacloud.jira.com/browse/COS-248

**Comment by kweerious** [comment]
Example test run with failing functional and logs working:

https://metacloud.jira.com/browse/COS-250

**Comment by kweerious** [comment]
Tested on Jenkins, result:

https://metacloud.jira.com/browse/COS-255

**Comment by kweerious** [comment]
@novas0x2a base urls removed and made into env vars.

**Comment by cimarron-pistoncloud** [comment]
Is it an issue that 
```
+ curl --retry 5 --retry-delay 5 -H 'Authorization: Basic cGlz(redacted)Y3M=' 
``` 
appears in the output of the link in the Jira ticket
Bug Filer Job: https://albino.piston.cc/job/X_Report_Failed_Test/6043/console
?

**Comment by kweerious** [comment]
@cimarron-pistoncloud I think it's this line that is responsible for outputting the results of each command in the shell script: 

    OUTPUT=$(bash "$WORKSPACE/file-bug.sh")
    if [ "$(echo "$OUTPUT" | egrep -i -v '"key": "COS-\w+"')" ]

But I think that's information we want to keep. Do you know an easy way to mask it that I'm missing?

**Comment by cimarron-pistoncloud** [comment]
I believe the text is from `set -x` which goes to stderr so to redact that something like
```
OUTPUT=$(bash "$WORKSPACE/file-bug.sh" 2> >(sed -e "s/'Authorization: [^']*'/(redacted)/g" 1>&2))
```
may work.  My bash-fu isn't very strong but @nbartos probably knows a better way.

**Comment by kweerious** [comment]
@cimarron-pistoncloud that worked! https://albino.piston.cc/job/X_Report_Failed_Test/6050/

**Comment by cimarron-pistoncloud** [comment]
Ya but you can still see JIRA_TOKEN=cGlzd...1Y3M= in there :-P 
Maybe this is better
```
OUTPUT=$(bash "log.sh" 2> >(sed -e "s/$JIRA_TOKEN/(redacted)/g" 1>&2))
```

**Comment by kweerious** [comment]
@cimarron-pistoncloud that still shows up with that sed line then.

https://albino.piston.cc/job/X_Report_Failed_Test/6052/console

**Comment by kweerious** [comment]
@cimarron-pistoncloud the token is going to show up regardless since it is an ENV var.

**Comment by cimarron-pistoncloud** [comment]
How about this?
```
set +x
OUTPUT=$(bash "$WORKSPACE/file-bug.sh" 2> >(sed -e "s/$JIRA_TOKEN/(redacted)/g" 1>&2))
set -x
```

**Comment by kweerious** [comment]
New version in Jenkins with scrubbed ENV vars and redacted output.

https://albino.piston.cc/job/X_Report_Failed_Test/6058/
https://metacloud.jira.com/browse/COS-259

**Pull request merged**
